load "mono.m";
t:=Cputime();
A:=atoii(A); B:=atoii(B); ell:=atoi(ell);
d:=Degree(A,B); w:=Weight(A,B);
r:=Rank(ChangeRing(BezoutMatrix(A,B),GF(ell)));
G:=AmbientIsometryGroup(A,B,ell); nG:=#G; gG:=[Eltseq(g):g in Generators(G)];
H:=MonodromyGroup(A,B,ell); nH:=#H; gH:=[Eltseq(h):h in Generators(H)];
s:=Sprintf("%o:%o:%o:%o:%o:%o:%o:%o:%o:%o:%o:%o:%.3o",A,B,ell,d,w,[d mod 2, w mod 2],r,nG,nH,nG/nH,gG,gH,Cputime()-t);
print strip(s);
exit;
